### PR TITLE
Added animation styles for use with ng-show.

### PR DESCRIPTION
**Pull request by sathishvj**
I added animation styles for use with ng-show directive.  I've also compiled it with koala to test it out locally, but you probably want to recompile it as you would usually.

### CODE REVIEW

**Comment by Augus** [comment]
Great job @sathishvj !

**Comment by e-oz** [comment]
thanks @sathishvj

**Comment by Augus** [comment]
@sathishvj  Can you give us a simple demo for this feature? thanks

**Comment by sathishvj** [comment]
Thanks Augus.  Cool, let me see if I can follow your index.html page to create a similar demo integrated with yours.

**Pull request merged**
